############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

#[[main]]
#name = "2024 Schedule"
#url = "previous_events/2024_04"
#weight = 3

[[main]]
name = "CFP"
url = "cfp/"
weight = 4
hasChildren = true

[[main]]
parent = "CFP"
weight = 1
name = "ComfyConAU CFP"
url = "cfp/"

[[main]]
parent = "CFP"
weight = 2
name = "CFP writing"
url = "cfp/cfp_writing/"

[[main]]
parent = "CFP"
weight = 3
name = "Speaker resources"
url = "cfp/speaker_resources/"

[[main]]
weight = 5
name = "Previous Events"
url = "previous_events/"
hasChildren = true

[[main]]
parent = "Previous Events"
weight = 1
name = "April 2020"
url = "previous_events/2020_04/"

[[main]]
parent = "Previous Events"
weight = 2
name = "November 2020"
url = "previous_events/2020_11"

[[main]]
parent = "Previous Events"
weight = 3
name = "April 2022"
url = "previous_events/2022_04"

[[main]]
parent = "Previous Events"
weight = 4
name = "November 2022"
url = "previous_events/2022_11/"

# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Code of Conduct"
url = "code-of-conduct/"
weight = 2
